/**
 * 题目扩展数据
 * 将每种题型从20道扩展到200道
 */

// 拼音练习扩展数据 (py021-py200)
const EXTENDED_PINYIN = [
  { id: 'py021', type: 'pinyin', question: '下列加点字读音全部相同的一项是：', options: ['A. 重要 重量 山重水复', 'B. 木拴 诠释 病情痊愈', 'C. 应酬 应对 得心应手', 'D. 谱写 铺垫 普天同庆'], correctAnswer: 1, analysis: 'B项全部读quán（栓、诠、痊）。' },
  { id: 'py022', type: 'pinyin', question: '"宿"在"宿舍"中读：', options: ['A. sù', 'B. xiù', 'C. xiǔ', 'D. shù'], correctAnswer: 0, analysis: '"宿"在"宿舍"中读sù。' },
  { id: 'py023', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 示意(yì) 自爆(bào)', 'B. 玉佩(pèi) 赶时髦(máo)', 'C. 编缉(jí) 凌分子(líng)', 'D. 果腹(fù) 金刚钻(zuàn)'], correctAnswer: 3, analysis: 'D项正确。A项"爆"应读bào；B项"髦"应读máo；C项"缉"应读jī。' },
  { id: 'py024', type: 'pinyin', question: '"抵御"的"御"读音是：', options: ['A. yù', 'B. xiè', 'C. yī', 'D. yè'], correctAnswer: 0, analysis: '"御"读yù。' },
  { id: 'py025', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 羊绒(róng) 梳子(shū)', 'B. 特定(dìng) 损害(sǔn)', 'C. 特制(zhì) 损伤(shāng)', 'D. 抵御(yù] 梳理(shū)'], correctAnswer: 2, analysis: 'C项"制"应读zhì，正确。本题C项无误。' },
  { id: 'py026', type: 'pinyin', question: '"兴"在"兴冲冲"中读：', options: ['A. xìng', 'B. xīng', 'C. xìn', 'D. xīn'], correctAnswer: 1, analysis: '"兴"在"兴冲冲"中读xīng。' },
  { id: 'py027', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 拦路虎(lǔ) 自爆自弃(bào)', 'B. 筹踞满志(jù) 妙趣横生(qù)', 'C. 编缉(jí) 凌分子(líng)', 'D. 相濡以沫(mò) 金刚钻(zuān)'], correctAnswer: 3, analysis: 'D项正确。' },
  { id: 'py028', type: 'pinyin', question: '"倔强"的"强"读：', options: ['A. qiáng', 'B. jiàng', 'C. qiǎng', 'D. jàng'], correctAnswer: 1, analysis: '"倔强"的"强"读jiàng。' },
  { id: 'py029', type: 'pinyin', question: '下列各组词语中加点字读音全都相同的一项是：', options: ['A. 哈欠 哈达 点头哈腰', 'B. 花苞 袍子 明碉暗堡', 'C. 好转 好歹 好逸恶劳', 'D. 巅峰 掂量 黑白颠倒'], correctAnswer: 0, analysis: 'A项都读hā。' },
  { id: 'py030', type: 'pinyin', question: '"记载"的"载"读：', options: ['A. zǎi', 'B. zài', 'C. zhǎi', 'D. zhài'], correctAnswer: 0, analysis: '"记载"的"载"读zǎi。' },
  { id: 'py031', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 编纂(zuǎn) 闷葫芦(mèn)', 'B. 偃旗息鼓(yǎn) 辐射(fú)', 'C. 峰窝煤(fēng) 雷厉风行(lì)', 'D. 灸手可热(zhì) 临摹(mó)'], correctAnswer: 1, analysis: 'B项正确。A项"纂"应读zuǎn；C项"峰"应读fēng；D项"灸"应读zhì。' },
  { id: 'py032', type: 'pinyin', question: '"创造"的"创"读：', options: ['A. chuàng', 'B. chuāng', 'C. chuàng', 'D. chuāng'], correctAnswer: 0, analysis: '"创造"的"创"读chuàng。' },
  { id: 'py033', type: 'pinyin', question: '下列词语中加点字读音完全相同的一项是：', options: ['A. 更迭 更加 改弦更张', 'B. 范畴 酬劳 运筹帷幄', 'C. 兴致 兴奋 云兴霞蔚', 'D. 弊端 瞥视 敝帚自珍'], correctAnswer: 1, analysis: 'B项都读chóu（畴、酬、筹）。' },
  { id: 'py034', type: 'pinyin', question: '"屏住"的"屏"读：', options: ['A. píng', 'B. bǐng', 'C. bǐn', 'D. pǐng'], correctAnswer: 1, analysis: '"屏住"的"屏"读bǐng。' },
  { id: 'py035', type: 'pinyin', question: '下列加点字注音有误的一项是：', options: ['A. 小心翼翼(yì) 作茧自缚(fù)', 'B. 蠢蠢欲动(chǔn) 参半(cān)', 'C. 归宿(sù) 如释重负(shì)', 'D. 浸渍(zì) 负载(zài)'], correctAnswer: 1, analysis: 'B项"参"应读cān正确。本题考查读音。' },
  { id: 'py036', type: 'pinyin', question: '"几许"的"几"读：', options: ['A. jī', 'B. jǐ', 'C. jī', 'D. jǐ'], correctAnswer: 1, analysis: '"几许"的"几"读jǐ。' },
  { id: 'py037', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 角逐(jué) 角色(jiǎo) 勾心斗角(jiǎo)', 'B. 供职(gòng) 供养(gòng) 供不应求(gōng)', 'C. 竞相(xiāng) 相左(xiāng) 相提并论(xiāng)', 'D. 几次三番(jǐ) 茶几(jī) 几许(jǐ)'], correctAnswer: 2, analysis: 'C项都读xiāng。' },
  { id: 'py038', type: 'pinyin', question: '"请缨"的"缨"读：', options: ['A. yīng', 'B. yīn', 'C. yǐng', 'D. yìn'], correctAnswer: 0, analysis: '"请缨"的"缨"读yīng。' },
  { id: 'py039', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 间奏曲(jiàn) 戮力同心(lù)', 'B. 荣膺(yīng) 殊不知(shū)', 'C. 请樱(qīng) 甚器尘上(shāng)', 'D. 问鼎(dǐng) 逆时针(nì)'], correctAnswer: 2, analysis: 'C项"樱"应读yīng，"请缨"正确。' },
  { id: 'py040', type: 'pinyin', question: '"导向"的"导"读：', options: ['A. dǎo', 'B. dào', 'C. dǎo', 'D. dào'], correctAnswer: 1, analysis: '"导向"的"导"读dǎo。' },
  { id: 'py041', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 转移(zhuǎn) 解释(shì)', 'B. 改良(liáng) 转变(zhuǎn)', 'C. 解决(jué) 策略(cè)', 'D. 发展(zhǎn) 议题(yì)'], correctAnswer: 2, analysis: 'C项正确。' },
  { id: 'py042', type: 'pinyin', question: '"鲜见"的"鲜"读：', options: ['A. xiān', 'B. xiǎn', 'C. xiān', 'D. xiǎn'], correctAnswer: 1, analysis: '"鲜见"的"鲜"读xiǎn。' },
  { id: 'py043', type: 'pinyin', question: '下列加点字读音完全相同的一项是：', options: ['A. 打开天窗说亮话 长线钓大鱼 羊毛出在羊身上', 'B. 当面锣对面锣 闪烁其词 捉摸不透', 'C. 八字没一瞥 唱对台戏 三下五除二', 'D. 不费吹灰之力 触目惊心 始作俑者'], correctAnswer: 0, analysis: '考查熟语中字的读音。' },
  { id: 'py044', type: 'pinyin', question: '"称职"的"称"读：', options: ['A. chēng', 'B. chèn', 'C. chēng', 'D. chèn'], correctAnswer: 1, analysis: '"称职"的"称"读chèn。' },
  { id: 'py045', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 兼容并蓄(bìng xù) 销声匿迹(xiāo)', 'B. 始作俑者(yǒng) 力挽狂澜(lán)', 'C. 众说纷纭(yún) 见仁见智(zhì)', 'D. 触目惊心(chù) 别开生面(shēng)'], correctAnswer: 1, analysis: 'B项正确。' },
  { id: 'py046', type: 'pinyin', question: '"混淆"的"淆"读：', options: ['A. xiáo', 'B. yáo', 'C. xiào', 'D. yào'], correctAnswer: 0, analysis: '"混淆"的"淆"读xiáo。' },
  { id: 'py047', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 运用人工智能(ji) 思考(sī)', 'B. 关乎团队(tuán) 国家(jiā)', 'C. 仪式(yí) 特征(tēng)', 'D. 明星效yìng(xiào) 商业价值(jià)'], correctAnswer: 2, analysis: 'C项"征"应读zhēng。' },
  { id: 'py048', type: 'pinyin', question: '"载誉"的"载"读：', options: ['A. zǎi', 'B. zài', 'C. zhǎi', 'D. zhài'], correctAnswer: 1, analysis: '"载誉"的"载"读zài。' },
  { id: 'py049', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 载誉(zài) 负载(zài)', 'B. 记载(zài) 刊载(zǎi)', 'C. 千年万载(zǎi) 载歌载舞(zài)', 'D. 怨声载道(zài) 载体(zài)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py050', type: 'pinyin', question: '"拓"在"拓片"中读：', options: ['A. tuò', 'B. tà', 'C. tuò', 'D. tà'], correctAnswer: 1, analysis: '"拓片"的"拓"读tà。' },
  { id: 'py051', type: 'pinyin', question: '下列加点字读音完全相同的一项是：', options: ['A. 剥皮 剥削 剥离', 'B. 薄弱 薄酒 薄暮', 'C. 参差 参拜 参军', 'D. 强迫 强调 强大'], correctAnswer: 0, analysis: 'A项都读bāo。' },
  { id: 'py052', type: 'pinyin', question: "'露马脚'的'露'读：', options: ['A. lù', 'B. lòu', 'C. lù', 'D. lòu'], correctAnswer: 1, analysis: "'露马脚'的'露'读lòu。' },
  { id: 'py053', type: 'pinyin', question: '下列加点字注音有误的一项是：', options: ['A. 奔跑(bēn) 投奔(bèn)', 'B. 闷热(mēn) 闷雷(mèn)', 'C. 参军(cān) 人参(shēn)', 'D. 强壮(qiáng) 倔强(jiàng)'], correctAnswer: 2, analysis: 'C项"参"应读cān正确。' },
  { id: 'py054', type: 'pinyin', question: '"巷道"的"巷"读：', options: ['A. xiàng', 'B. hàng', 'C. xiàng', 'D. hàng'], correctAnswer: 1, analysis: '"巷道"的"巷"读hàng。' },
  { id: 'py055', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 万万人空巷(xiàng) 巷道(hàng)', 'B. 静巷(xiàng) 巷战(xiàng)', 'C. 小巷(xiàng) 巷子(xiàng)', 'D. 街巷(xiàng) 巷口(xiàng)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py056', type: 'pinyin', question: '"亲家"的"亲"读：', options: ['A. qīn', 'B. qìng', 'C. qīn', 'D. qìng'], correctAnswer: 1, analysis: '"亲家"的"亲"读qìng。' },
  { id: 'py057', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 亲热(qīn) 亲近(qīn)', 'B. 亲家(qìng) 亲眷(qìng)', 'C. 亲自(qīn) 亲笔(qīn)', 'D. 亲切(qiè) 亲情(qíng)'], correctAnswer: 3, analysis: 'D项"切"应读qiè，"情"应读qíng。' },
  { id: 'py058', type: 'pinyin', question: '"巷子"的"巷"读：', options: ['A. hàng', 'B. xiàng', 'C. hàng', 'D. xiàng'], correctAnswer: 1, analysis: '"巷子"的"巷"读xiàng。' },
  { id: 'py059', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 因为(wèi) 为何(wéi)', 'B. 为人(wéi) 为了(wèi)', 'C. 为难(wéi) 为止(wéi)', 'D. 认为(wéi) 认为(wèi)'], correctAnswer: 1, analysis: 'B项正确。' },
  { id: 'py060', type: 'pinyin', question: '"吓唬"的"吓"读：', options: ['A. xià', 'B. hè', 'C. xià', 'D. hè'], correctAnswer: 0, analysis: '"吓唬"的"吓"读xià。' },
  { id: 'py061', type: 'pinyin', question: '下列加点字读音完全相同的一项是：', options: ['A. 吓唬(xià) 吓人(xià)', 'B. 恐吓(hè) 威吓(hè)', 'C. 威胁(xié) 胁持(xié)', 'D. 胁从(xié) 胁迫(xié)'], correctAnswer: 0, analysis: 'A项都读xià。' },
  { id: 'py062', type: 'pinyin', question: '"压轴"的"轴"读：', options: ['A. zhòu', 'B. zhóu', 'C. zhòu', 'D. zhóu'], correctAnswer: 0, analysis: '"压轴"的"轴"读zhòu。' },
  { id: 'py063', type: 'pinyin', question: '下列加点字注音有误的一项是：', options: ['A. 压轴(zhòu) 轴心(zhóu)', 'B. 轴承(zhóu) 地轴(zhóu)', 'C. 轴线(zhóu) 车轴(zhóu)', 'D. 压轴戏(zhòu) 主轴(zhóu)'], correctAnswer: 3, analysis: 'D项"主轴"应读zhóu，"压轴"读zhòu。' },
  { id: 'py064', type: 'pinyin', question: '"埋伏"的"埋"读：', options: ['A. mái', 'B. mán', 'C. mái', 'D. mán'], correctAnswer: 0, analysis: '"埋伏"的"埋"读mái。' },
  { id: 'py065', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 埋怨(mái) 埋伏(mái)', 'B. 埋藏(mái) 隐埋(mái)', 'C. 埋没(mái) 埋头(mái)', 'D. 埋怨(mán) 埋藏(mái)'], correctAnswer: 3, analysis: 'D项正确。"埋怨"的"埋"读mán。' },
  { id: 'py066', type: 'pinyin', question: '"劳累"的"累"读：', options: ['A. lèi', 'B. lěi', 'C. lèi', 'D. lěi'], correctAnswer: 0, analysis: '"劳累"的"累"读lèi。' },
  { id: 'py067', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 劳累(lèi) 受累(lèi)', 'B. 累计(lěi) 连累(lěi)', 'C. 累赘(léi) 果累(léi)', 'D. 牵累(lěi) 累及(lěi)'], correctAnswer: 2, analysis: 'C项"累赘"的"累"读léi。' },
  { id: 'py068', type: 'pinyin', question: '"模样"的"模"读：', options: ['A. mó', 'B. mú', 'C. mó', 'D. mú'], correctAnswer: 1, analysis: '"模样"的"模"读mú。' },
  { id: 'py069', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 模型(mó) 模样(mú)', 'B. 模仿(mó) 模糊(mó)', 'C. 模具(mú) 模范(mó)', 'D. 模样(mó) 模拟(mó)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py070', type: 'pinyin', question: '"颤动"的"颤"读：', options: ['A. chàn', 'B. zhàn', 'C. chàn', 'D. zhàn'], correctAnswer: 0, analysis: '"颤动"的"颤"读chàn。' },
  { id: 'py071', type: 'pinyin', question: '下列加点字读音完全相同的一项是：', options: ['A. 颤动(chàn) 颤抖(chàn)', 'B. 颤栗(zhàn) 颤巍巍(zhàn)', 'C. 颤音(chàn) 颤悠(chàn)', 'D. 颤动(zhàn) 颤抖(zhàn)'], correctAnswer: 0, analysis: 'A项都读chàn。' },
  { id: 'py072', type: 'pinyin', question: '"瓦砾"的"砾"读：', options: ['A. lì', 'B. lè', 'C. shuò', 'D. luò'], correctAnswer: 0, analysis: '"瓦砾"的"砾"读lì。' },
  { id: 'py073', type: 'pinyin', question: '下列加点字注音有误的一项是：', options: ['A. 瓦砾(lì) 砾石(lì)', 'B. 砂砾(lì) 砾土(lì)', 'C. 碎砾(lì) 砾岩(lì)', 'D. 砾砾(lì) 砾漠(lì)'], correctAnswer: 3, analysis: 'D项正确。' },
  { id: 'py074', type: 'pinyin', question: '"殷红"的"殷"读：', options: ['A. yīn', 'B. yān', 'C. yǐn', 'D. yān'], correctAnswer: 1, analysis: '"殷红"的"殷"读yān。' },
  { id: 'py075', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 殷勤(yīn) 殷红(yān)', 'B. 殷实(yīn) 殷切(yīn)', 'C. 殷殷(yīn) 殷商(yīn)', 'D. 殷红(yīn) 殷切(qiè)'], correctAnswer: 0, analysis: 'A项正确。"殷红"的"殷"读yān。' },
  { id: 'py076', type: 'pinyin', question: '"遂愿"的"遂"读：', options: ['A. suí', 'B. suì', 'C. suí', 'D. suì'], correctAnswer: 1, analysis: '"遂愿"的"遂"读suì。' },
  { id: 'py077', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 遂心(suì) 遂意(suì)', 'B. 半遂(suí) 遂愿(suì)', 'C. 遂顺(suí) 遂心(suì)', 'D. 顺遂(suí) 遂愿(suì)'], correctAnswer: 2, analysis: 'C项"遂顺"的"遂"读suí。' },
  { id: 'py078', type: 'pinyin', question: '"蜷缩"的"蜷"读：', options: ['A. juǎn', 'B. quán', 'C. juǎn', 'D. quán'], correctAnswer: 1, analysis: '"蜷缩"的"蜷"读quán。' },
  { id: 'py079', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 蜷曲(quán) 蜷缩(quán)', 'B. 蜷体(quán) 蜷卧(quán)', 'C. 蜷身(quán) 蜷腿(quán)', 'D. 蜷坐(quán) 蜷伏(quán)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py080', type: 'pinyin', question: '"剽悍"的"剽"读：', options: ['A. piāo', 'B. biāo', 'C. piáo', 'D. piào'], correctAnswer: 0, analysis: '"剽悍"的"剽"读piāo。' },
  { id: 'py081', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 剽悍(piāo) 剽窃(piāo)', 'B. 剽掠(piāo) 剽袭(piāo)', 'C. 剽攻(piāo) 剽取(piāo)', 'D. 剽悍(biāo) 剽掠(piāo)'], correctAnswer: 3, analysis: 'D项"剽悍"的"剽"应读piāo。' },
  { id: 'py082', type: 'pinyin', question: '"龃龉"的读音是：', options: ['A. jǔ yǔ', 'B. jǔ yǔ', 'C. jǔ yǔ', 'D. jǔ yǔ'], correctAnswer: 0, analysis: '"龃龉"读jǔ yǔ。' },
  { id: 'py083', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 踟躇(chú) 踯躅(zhú)', 'B. 踌躇(chú) 踌躇(chú)', 'C. 踌躇(chú) 踯躅(zhú)', 'D. 踟躇(zhī) 踌躇(chú)'], correctAnswer: 1, analysis: 'B项正确。' },
  { id: 'py084', type: 'pinyin', question: '"旖旎"的读音是：', options: ['A. yī nǐ', 'B. yǐ nǐ', 'C. yī nì', 'D. yǐ nì'], correctAnswer: 1, analysis: '"旖旎"读yǐ nǐ。' },
  { id: 'py085', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 旖旎(yǐ nǐ) 旖旎风光(yǐ)', 'B. 旎丽(nǐ lì) 旖旎(nǐ)', 'C. 旎子(nǐ zi) 旎丽(nǐ)', 'D. 旖旎(yī nǐ) 旖旎(yǐ)'], correctAnswer: 3, analysis: 'D项"旖"应读yǐ。' },
  { id: 'py086', type: 'pinyin', question: '"氤氲"的读音是：', options: ['A. yīn yūn', 'B. yīn yūn', 'C. yīn yūn', 'D. yīn yūn'], correctAnswer: 0, analysis: '"氤氲"读yīn yūn。' },
  { id: 'py087', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 氤氲(yīn) 氤氲(yūn)', 'B. 氤氲(yīn) 氲气(yūn)', 'C. 氤氲(yīn) 氤氲(yūn)', 'D. 氤氲(yīn) 氲云(yūn)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py088', type: 'pinyin', question: '"孑孓"的读音是：', options: ['A. jié jué', 'B. jié jué', 'C. jié jué', 'D. jié jué'], correctAnswer: 0, analysis: '"孑孓"读jié jué。' },
  { id: 'py089', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 孑然(jié) 孑孓(jié)', 'B. 孑遗(jié) 孑民(jié)', 'C. 孑身(jié) 孑立(jié)', 'D. 孑孓(jué) 孑然(jié)'], correctAnswer: 3, analysis: 'D项"孑孓"的"孓"应读jué。' },
  { id: 'py090', type: 'pinyin', question: '"孑孓"的意思是：', options: ['A. 蚊子的幼虫', 'B. 孤独的样子', 'C. 微小的样子', 'D. 残留的'], correctAnswer: 0, analysis: '"孑孓"指蚊子的幼虫。' },
  { id: 'py091', type: 'pinyin', question: '"拮据"的读音是：', options: ['A. jié jū', 'B. jié jù', 'C. jí jū', 'D. jí jù'], correctAnswer: 0, analysis: '"拮据"读jié jū。' },
  { id: 'py092', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 拮据(jié jū) 据守(jù)', 'B. 拮据(jí jū) 占据(jù)', 'C. 拮据(jié jū) 根据(jù)', 'D. 拮据(jí jū) 依据(jù)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py093', type: 'pinyin', question: '"讪笑"的"讪"读：', options: ['A. shàn', 'B. shān', 'C. shàn', 'D. shān'], correctAnswer: 0, analysis: '"讪笑"的"讪"读shàn。' },
  { id: 'py094', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 讪笑(shàn) 讪讪(shàn)', 'B. 讪然(shàn) 讪皮(shàn)', 'C. 讪脸(shàn) 讪骂(shàn)', 'D. 讪笑(shān) 讪然(shàn)'], correctAnswer: 3, analysis: 'D项"讪笑"的"讪"应读shàn。' },
  { id: 'py095', type: 'pinyin', question: '"挑衅"的"衅"读：', options: ['A. xìn', 'B. xīn', 'C. xìn', 'D. xīn'], correctAnswer: 0, analysis: '"挑衅"的"衅"读xìn。' },
  { id: 'py096', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 挑衅(xìn) 寻衅(xìn)', 'B. 挑衅(xīn) 争衅(xìn)', 'C. 挑衅(xìn) 衅事(xìn)', 'D. 挑衅(xīn) 肇衅(xìn)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py097', type: 'pinyin', question: '"殷"在"殷实"中读：', options: ['A. yīn', 'B. yān', 'C. yǐn', 'D. yān'], correctAnswer: 0, analysis: '"殷实"的"殷"读yīn。' },
  { id: 'py098', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 殷实(yīn) 殷勤(yīn)', 'B. 殷切(yīn) 殷殷(yīn)', 'C. 殷红(yān) 殷商(yīn)', 'D. 殷实(yān) 殷切(yīn)'], correctAnswer: 3, analysis: 'D项"殷实"的"殷"应读yīn。' },
  { id: 'py099', type: 'pinyin', question: '"氛围"的"氛"读：', options: ['A. fēn', 'B. fèn', 'C. fēn', 'D. fèn'], correctAnswer: 0, analysis: '"氛围"的"氛"读fēn。' },
  { id: 'py100', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 氛围(fēn) 气氛(fēn)', 'B. 氛围(fèn) 氛围(fēn)', 'C. 气氛(fèn) 氛围(fēn)', 'D. 氛围(fēn) 氛围(fèn)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py101', type: 'pinyin', question: '"龟裂"的"龟"读：', options: ['A. guī', 'B. jūn', 'C. guī', 'D. jūn'], correctAnswer: 1, analysis: '"龟裂"的"龟"读jūn。' },
  { id: 'py102', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 龟裂(jūn) 龟裂(jūn)', 'B. 龟裂(guī) 乌龟(guī)', 'C. 龟裂(jūn) 龟裂(guī)', 'D. 龟裂(guī) 龟裂(jūn)'], correctAnswer: 2, analysis: 'C项"龟裂"的"龟"应读jūn。' },
  { id: 'py103', type: 'pinyin', question: '"确凿"的"凿"读：', options: ['A. záo', 'B. zuò', 'C. záo', 'D. zuò'], correctAnswer: 0, analysis: '"确凿"的"凿"读záo。' },
  { id: 'py104', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 确凿(záo) 开凿(záo)', 'B. 确凿(zuò) 凿子(záo)', 'C. 确凿(záo) 凿井(záo)', 'D. 确凿(zuò) 凿通(záo)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py105', type: 'pinyin', question: '"菡萏"的读音是：', options: ['A. hàn dàn', 'B. hán dàn', 'C. hàn dán', 'D. hán dán'], correctAnswer: 0, analysis: '"菡萏"读hàn dàn。' },
  { id: 'py106', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 菡萏(hàn dàn) 菡萏(hàn)', 'B. 菡萏(hán dàn) 菡萏香(hàn)', 'C. 菡萏(hàn dàn) 菡萏(hán)', 'D. 菡萏(hán dàn) 菡萏(hàn)'], correctAnswer: 2, analysis: 'C项正确。' },
  { id: 'py107', type: 'pinyin', question: '"栖息"的"栖"读：', options: ['A. qī', 'B. xī', 'C. qī', 'D. xī'], correctAnswer: 0, analysis: '"栖息"的"栖"读qī。' },
  { id: 'py108', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 栖息(qī) 栖身(qī)', 'B. 栖息(xī) 栖息(qī)', 'C. 栖息(qī) 栖居(qī)', 'D. 栖息(xī) 栖身(qī)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py109', type: 'pinyin', question: '"伛偻"的读音是：', options: ['A. yǔ lǚ', 'B. yǔ lóu', 'C. yū lǚ', 'D. yū lóu'], correctAnswer: 0, analysis: '"伛偻"读yǔ lǚ。' },
  { id: 'py110', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 伛偻(yǔ lǚ) 伛偻(yǔ)', 'B. 伛偻(lǚ) 伛偻(yǔ)', 'C. 伛偻(yǔ lóu) 伛偻(yǔ)', 'D. 伛偻(yǔ lǚ) 伛偻(lǚ)'], correctAnswer: 2, analysis: 'C项"伛偻"的"偻"应读lǚ。' },
  { id: 'py111', type: 'pinyin', question: '"骊歌"的"骊"读：', options: ['A. lí', 'B. lì', 'C. lí', 'D. lì'], correctAnswer: 0, analysis: '"骊歌"的"骊"读lí。' },
  { id: 'py112', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 骊歌(lí) 骊山(lí)', 'B. 骊歌(lì) 骊珠(lí)', 'C. 骊歌(lí) 骊龙(lí)', 'D. 骊歌(lì) 骊山(lí)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py113', type: 'pinyin', question: '"逾越"的"逾"读：', options: ['A. yú', 'B. yù', 'C. yú', 'D. yù'], correctAnswer: 1, analysis: '"逾越"的"逾"读yù。' },
  { id: 'py114', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 逾越(yù) 逾越(yú)', 'B. 逾越(yù) 逾期(yú)', 'C. 逾越(yù) 逾垣(yú)', 'D. 逾越(yú) 逾越(yù)'], correctAnswer: 3, analysis: 'D项"逾越"的"逾"应读yù。' },
  { id: 'py115', type: 'pinyin', question: '"缄默"的"缄"读：', options: ['A. jiān', 'B. jiǎn', 'C. jiān', 'D. jiǎn'], correctAnswer: 0, analysis: '"缄默"的"缄"读jiān。' },
  { id: 'py116', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 缄默(jiān) 缄口(jiān)', 'B. 缄默(jiǎn) 缄默(jiān)', 'C. 缄默(jiān) 缄口(jiǎn)', 'D. 缄默(jiǎn) 缄口(jiǎn)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py117', type: 'pinyin', question: '"盔甲"的"盔"读：', options: ['A. kuī', 'B. kuí', 'C. kuī', 'D. kuí'], correctAnswer: 0, analysis: '"盔甲"的"盔"读kuī。' },
  { id: 'py118', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 盔甲(kuī) 盔甲(kuí)', 'B. 盔甲(kuī) 盔头(kuí)', 'C. 盔甲(kuí) 盔甲(kuī)', 'D. 盔甲(kuī) 盔头(kuī)'], correctAnswer: 2, analysis: 'C项"盔甲"的"盔"应读kuī。' },
  { id: 'py119', type: 'pinyin', question: '"阔绰"的"绰"读：', options: ['A. chuò', 'B. chāo', 'C. chuò', 'D. chāo'], correctAnswer: 0, analysis: '"阔绰"的"绰"读chuò。' },
  { id: 'py120', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 阔绰(chuò) 绰号(chuò)', 'B. 阔绰(chāo) 绰约(chuò)', 'C. 阔绰(chuò) 绰绰(chuò)', 'D. 阔绰(chāo) 绰号(chāo)'], correctAnswer: 0, analysis: 'A项正确。"绰号"的"绰"读chuò。' },
  { id: 'py121', type: 'pinyin', question: '"吝啬"的读音是：', options: ['A. lìn sè', 'B. lìn sāi', 'C. lìng sè', 'D. lìng sāi'], correctAnswer: 0, analysis: '"吝啬"读lìn sè。' },
  { id: 'py122', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 吝啬(lìn sè) 吝惜(lìn)', 'B. 吝啬(lìn sè) 吝色(lìn)', 'C. 吝啬(lìn sè) 吝啬(lìn)', 'D. 吝啬(lìn sāi) 吝惜(lìn)'], correctAnswer: 3, analysis: 'D项"吝啬"的"啬"应读sè。' },
  { id: 'py123', type: 'pinyin', question: '"絮说"的"絮"读：', options: ['A. xù', 'B. xǔ', 'C. xù', 'D. xǔ'], correctAnswer: 0, analysis: '"絮说"的"絮"读xù。' },
  { id: 'py124', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 絮说(xù) 絮叨(xù)', 'B. 絮说(xǔ) 絮烦(xù)', 'C. 絮说(xù) 絮絮(xù)', 'D. 絮说(xǔ) 絮叨(xǔ)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py125', type: 'pinyin', question: '"踌躇"的读音是：', options: ['A. chóu chú', 'B. chóu chú', 'C. chóu chú', 'D. chóu chú'], correctAnswer: 0, analysis: '"踌躇"读chóu chú。' },
  { id: 'py126', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 踌躇(chóu chú) 踌躇(chóu)', 'B. 踌躇(chú chú) 踌躇(chóu)', 'C. 踌躇(chóu chú) 踌躇(chú)', 'D. 踌躇(chóu chú) 踌躇(chóu)'], correctAnswer: 1, analysis: 'B项"踌躇"的"踌"应读chóu。' },
  { id: 'py127', type: 'pinyin', question: '"颓唐"的读音是：', options: ['A. tuí táng', 'B. tuí táng', 'C. tuí táng', 'D. tuí táng'], correctAnswer: 0, analysis: '"颓唐"读tuí táng。' },
  { id: 'py128', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 颓唐(tuí) 颓废(tuí)', 'B. 颓唐(tuí) 颓丧(tuí)', 'C. 颓唐(tuí) 颓败(tuí)', 'D. 颓唐(tuí) 颓靡(tuí)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py129', type: 'pinyin', question: '"惊惶"的"惶"读：', options: ['A. huáng', 'B. huāng', 'C. huáng', 'D. huāng'], correctAnswer: 0, analysis: '"惊惶"的"惶"读huáng。' },
  { id: 'py130', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 惊惶(huáng) 惶恐(huáng)', 'B. 惊惶(huáng) 惶惑(huáng)', 'C. 惊惶(huāng) 惶遽(huáng)', 'D. 惊惶(huáng) 惶惶(huáng)'], correctAnswer: 2, analysis: 'C项"惊惶"的"惶"应读huáng。' },
  { id: 'py131', type: 'pinyin', question: '"蹒跚"的读音是：', options: ['A. pán shān', 'B. pán shān', 'C. pán shān', 'D. pán shān'], correctAnswer: 0, analysis: '"蹒跚"读pán shān。' },
  { id: 'py132', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 蹒跚(pán) 蹒跚(shān)', 'B. 蹒跚(pán) 蹒跚(pán)', 'C. 蹒跚(pán) 蹒跚(shān)', 'D. 蹒跚(pán) 蹒跚(pán)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py133', type: 'pinyin', question: '"伫立"的"伫"读：', options: ['A. zhù', 'B. zhǔ', 'C. zhù', 'D. zhǔ'], correctAnswer: 0, analysis: '"伫立"的"伫"读zhù。' },
  { id: 'py134', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 伫立(zhù) 伫立(zhù)', 'B. 伫立(zhǔ) 伫候(zhù)', 'C. 伫立(zhù) 伫望(zhù)', 'D. 伫立(zhù) 伫立(zhǔ)'], correctAnswer: 3, analysis: 'D项"伫立"的"伫"应读zhù。' },
  { id: 'py135', type: 'pinyin', question: '"粗糙"的"糙"读：', options: ['A. cāo', 'B. zào', 'C. cāo', 'D. zào'], correctAnswer: 0, analysis: '"粗糙"的"糙"读cāo。' },
  { id: 'py136', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 粗糙(cāo) 糙米(cāo)', 'B. 粗糙(cāo) 糁糙(zào)', 'C. 粗糙(cāo) 糙汉(cāo)', 'D. 粗糙(zào) 糙米(cāo)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py137', type: 'pinyin', question: '"唯妙唯肖"应为：', options: ['A. 惟妙惟肖', 'B. 唯妙唯肖', 'C. 维妙维肖', 'D. 微妙微肖'], correctAnswer: 0, analysis: '应为"惟妙惟肖"。' },
  { id: 'py138', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 惟妙惟肖(xiào) 惟妙(wéi)', 'B. 惟妙惟肖(xiāo) 惟妙(wéi)', 'C. 惟妙惟肖(xiào) 惟妙(wéi)', 'D. 惟妙惟肖(xiāo) 惟妙(wéi)'], correctAnswer: 1, analysis: 'B项"肖"应读xiào。' },
  { id: 'py139', type: 'pinyin', question: '"嗔视"的"嗔"读：', options: ['A. chēn', 'B. chēng', 'C. chēn', 'D. chēng'], correctAnswer: 0, analysis: '"嗔视"的"嗔"读chēn。' },
  { id: 'py140', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 嗔视(chēn) 嗔怪(chēn)', 'B. 嗔视(chēng) 嗔怒(chēn)', 'C. 嗔视(chēn) 嗔怪(chēng)', 'D. 嗔视(chēng) 嗔怒(chēng)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py141', type: 'pinyin', question: '"娴熟"的"娴"读：', options: ['A. xián', 'B. xiān', 'C. xián', 'D. xiān'], correctAnswer: 0, analysis: '"娴熟"的"娴"读xián。' },
  { id: 'py142', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 娴熟(xián) 娴熟(xián)', 'B. 娴熟(xiān) 娴雅(xián)', 'C. 娴熟(xián) 娴静(xián)', 'D. 娴熟(xiān) 娴熟(xián)'], correctAnswer: 3, analysis: 'D项"娴熟"的"娴"应读xián。' },
  { id: 'py143', type: 'pinyin', question: '"惩罚"的"惩"读：', options: ['A. chéng', 'B. chěng', 'C. chéng', 'D. chěng'], correctAnswer: 0, analysis: '"惩罚"的"惩"读chéng。' },
  { id: 'py144', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 惩罚(chéng) 惩治(chéng)', 'B. 惩罚(chěng) 惩戒(chéng)', 'C. 惩罚(chéng) 惩处(chǔ)', 'D. 惩罚(chěng) 惩治(chěng)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py145', type: 'pinyin', question: '"畸形"的"畸"读：', options: ['A. jī', 'B. jí', 'C. jī', 'D. jí'], correctAnswer: 0, analysis: '"畸形"的"畸"读jī。' },
  { id: 'py146', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 畸形(jī) 畸形(jī)', 'B. 畸形(jí) 畸变(jī)', 'C. 畸形(jī) 畸轻畸重(jī)', 'D. 畸形(jí) 畸形(jī)'], correctAnswer: 3, analysis: 'D项"畸形"的"畸"应读jī。' },
  { id: 'py147', type: 'pinyin', question: '"媲美"的"媲"读：', options: ['A. pì', 'B. bǐ', 'C. pì', 'D. bǐ'], correctAnswer: 0, analysis: '"媲美"的"媲"读pì。' },
  { id: 'py148', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 媲美(pì) 媲美(pì)', 'B. 媲美(pí) 媲美(pì)', 'C. 媲美(pì) 媲配(pì)', 'D. 媲美(pí) 媲配(pí)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py149', type: 'pinyin', question: '"狩猎"的"狩"读：', options: ['A. shòu', 'B. shǒu', 'C. shòu', 'D. shǒu'], correctAnswer: 0, analysis: '"狩猎"的"狩"读shòu。' },
  { id: 'py150', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 狩猎(shòu) 狩猎(shòu)', 'B. 狩猎(shòu) 狩狩(shòu)', 'C. 狩猎(shǒu) 狩猎(shòu)', 'D. 狩猎(shòu) 狩猎(shǒu)'], correctAnswer: 2, analysis: 'C项"狩猎"的"狩"应读shòu。' },
  { id: 'py151', type: 'pinyin', question: '"褶皱"的"褶"读：', options: ['A. zhě', 'B. zhé', 'C. zhě', 'D. zhé'], correctAnswer: 0, analysis: '"褶皱"的"褶"读zhě。' },
  { id: 'py152', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 褶皱(zhě) 褶子(zhě)', 'B. 褶皱(zhé) 褶皱(zhě)', 'C. 褶皱(zhě) 褶皱(zhé)', 'D. 褶皱(zhé) 褶子(zhé)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py153', type: 'pinyin', question: '"贮蓄"的"贮"读：', options: ['A. zhù', 'B. chǔ', 'C. zhù', 'D. chǔ'], correctAnswer: 0, analysis: '"贮蓄"的"贮"读zhù。' },
  { id: 'py154', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 贮蓄(zhù) 贮存(zhù)', 'B. 贮蓄(zhù) 贮藏(zhù)', 'C. 贮蓄(chǔ) 贮蓄(zhù)', 'D. 贮蓄(zhù) 贮备(zhù)'], correctAnswer: 2, analysis: 'C项"贮蓄"的"贮"应读zhù。' },
  { id: 'py155', type: 'pinyin', question: '"酝酿"的读音是：', options: ['A. yùn niàng', 'B. yùn niàng', 'C. yǔn niàng', 'D. yǔn niàng'], correctAnswer: 0, analysis: '"酝酿"读yùn niàng。' },
  { id: 'py156', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 酝酿(yùn) 酝酿(niàng)', 'B. 酝酿(yǔn) 酝酿(niàng)', 'C. 酝酿(yùn) 酝酒(niàng)', 'D. 酝酿(yǔn) 酿酒(niàng)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py157', type: 'pinyin', question: '"菜畦"的"畦"读：', options: ['A. qí', 'B. wā', 'C. qí', 'D. wā'], correctAnswer: 0, analysis: '"菜畦"的"畦"读qí。' },
  { id: 'py158', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 菜畦(qí) 畦田(qí)', 'B. 菜畦(qí) 畦径(qí)', 'C. 菜畦(wā) 畦田(qí)', 'D. 菜畦(qí) 畦子(qí)'], correctAnswer: 2, analysis: 'C项"菜畦"的"畦"应读qí。' },
  { id: 'py159', type: 'pinyin', question: '"脑髓"的"髓"读：', options: ['A. suǐ', 'B. suī', 'C. suǐ', 'D. suī'], correctAnswer: 0, analysis: '"脑髓"的"髓"读suǐ。' },
  { id: 'py160', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 脑髓(suǐ) 骨髓(suǐ)', 'B. 脑髓(suī) 髓质(suǐ)', 'C. 脑髓(suǐ) 髓腔(suǐ)', 'D. 脑髓(suī) 骨髓(suī)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py161', type: 'pinyin', question: '"狡狞"应为：', options: ['A. 狰狞', 'B. 狡狞', 'C. 狞狰', 'D. 狞狡'], correctAnswer: 0, analysis: '应为"狰狞"。' },
  { id: 'py162', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 狰狞(níng) 狰狞(níng)', 'B. 狰狞(níng) 狰狞(níng)', 'C. 狰狞(ning) 狰狞(níng)', 'D. 狰狞(níng) 狰狞(níng)'], correctAnswer: 2, analysis: 'C项"狞"应读níng。' },
  { id: 'py163', type: 'pinyin', question: '"同仇敌忾"的"忾"读：', options: ['A. kài', 'B. qì', 'C. kài', 'D. qì'], correctAnswer: 0, analysis: '"同仇敌忾"的"忾"读kài。' },
  { id: 'py164', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 同仇敌忾(kài) 敌忾(kài)', 'B. 同仇敌忾(qì) 敌忾(kài)', 'C. 同仇敌忾(kài) 敌忾(qì)', 'D. 同仇敌忾(qì) 敌忾(qì)'], correctAnswer: 0, analysis: 'A项正确。' },
  { id: 'py165', type: 'pinyin', question: '"玷污"的"玷"读：', options: ['A. diàn', 'B. zhān', 'C. diàn', 'D. zhān'], correctAnswer: 0, analysis: '"玷污"的"玷"读diàn。' },
  { id: 'py166', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 玷污(diàn) 玷污(diàn)', 'B. 玷污(zhān) 玷辱(diàn)', 'C. 玷污(diàn) 玷污(zhān)', 'D. 玷污(diàn) 玷辱(diàn)'], correctAnswer: 2, analysis: 'C项"玷污"的"玷"应读diàn。' },
  { id: 'py167', type: 'pinyin', question: '"供给"的"供"读：', options: ['A. gōng', 'B. gòng', 'C. gōng', 'D. gòng'], correctAnswer: 1, analysis: '"供给"的"供"读gòng。' },
  { id: 'py168', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 供给(gòng) 供品(gòng)', 'B. 供给(gōng) 供认(gòng)', 'C. 供给(gòng) 供职(gòng)', 'D. 供给(gōng) 供认(gōng)'], correctAnswer: 0, analysis: 'A项正确。"供认"的"供"读gòng。' },
  { id: 'py169', type: 'pinyin', question: '"口角"的"角"读：', options: ['A. jué', 'B. jiǎo', 'C. jué', 'D. jiǎo'], correctAnswer: 1, analysis: '"口角"的"角"读jiǎo。' },
  { id: 'py170', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 口角(jiǎo) 角色(jué)', 'B. 口角(jué) 角逐(jué)', 'C. 口角(jiǎo) 角度(jiǎo)', 'D. 口角(jué) 角落(jiǎo)'], correctAnswer: 1, analysis: 'B项"口角"的"角"应读jiǎo。' },
  { id: 'py171', type: 'pinyin', question: '"倔强"的读音是：', options: ['A. jué jiàng', 'B. juè jiàng', 'C. jué jiàng', 'D. juè jiàng'], correctAnswer: 0, analysis: '"倔强"读jué jiàng。' },
  { id: 'py172', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 倔强(jiàng) 强迫(qiǎng)', 'B. 倔强(jiàng) 强壮(qiáng)', 'C. 倔强(jué) 强迫(qiáng)', 'D. 倔强(jiàng) 强大(qiáng)'], correctAnswer: 1, analysis: 'B项正确。"倔强"读jué jiàng。' },
  { id: 'py173', type: 'pinyin', question: '"处分"的"处"读：', options: ['A. chǔ', 'B. chù', 'C. chǔ', 'D. chù'], correctAnswer: 1, analysis: '"处分"的"处"读chù。' },
  { id: 'py174', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 处分(chù) 处理(chǔ)', 'B. 处分(chù) 处所(chù)', 'C. 处分(chǔ) 处置(chǔ)', 'D. 处分(chù) 处所(chù)'], correctAnswer: 2, analysis: 'C项"处分"的"处"应读chù。' },
  { id: 'py175', type: 'pinyin', question: '"处所"的"处"读：', options: ['A. chǔ', 'B. chù', 'C. chǔ', 'D. chù'], correctAnswer: 1, analysis: '"处所"的"处"读chù。' },
  { id: 'py176', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 处所(chù) 住处(chù)', 'B. 处所(chù) 好处(chù)', 'C. 处所(chù) 去处(chù)', 'D. 处所(chù) 处方(chù)'], correctAnswer: 0, analysis: 'A项正确。"处方"的"处"读chǔ。' },
  { id: 'py177', type: 'pinyin', question: '"恶劣"的"恶"读：', options: ['A. è', 'B. wù', 'C. è', 'D. wù'], correctAnswer: 0, analysis: '"恶劣"的"恶"读è。' },
  { id: 'py178', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 恶劣(è) 恶心(ě)', 'B. 恶劣(è) 凶恶(è)', 'C. 恶劣(wù) 恶习(è)', 'D. 恶劣(è) 善恶(è)'], correctAnswer: 2, analysis: 'C项"恶劣"的"恶"应读è。' },
  { id: 'py179', type: 'pinyin', question: '"恶心"的"恶"读：', options: ['A. è', 'B. ě', 'C. è', 'D. ě'], correctAnswer: 1, analysis: '"恶心"的"恶"读ě。' },
  { id: 'py180', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 恶心(ě) 恶心(ě)', 'B. 恶心(ě) 厌恶(wù)', 'C. 恶心(ě) 可恶(wù)', 'D. 恶心(è) 厌恶(wù)'], correctAnswer: 0, analysis: 'A项正确。"厌恶"的"恶"读wù。' },
  { id: 'py181', type: 'pinyin', question: '"称职"的"称"读：', options: ['A. chēng', 'B. chèn', 'C. chēng', 'D. chèn'], correctAnswer: 1, analysis: '"称职"的"称"读chèn。' },
  { id: 'py182', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 称职(chèn) 称赞(chēng)', 'B. 称职(chèn) 称心(chèn)', 'C. 称职(chēng) 称量(chēng)', 'D. 称职(chèn) 相称(chèn)'], correctAnswer: 2, analysis: 'C项"称职"的"称"应读chèn。' },
  { id: 'py183', type: 'pinyin', question: '"假期"的"假"读：', options: ['A. jiǎ', 'B. jià', 'C. jiǎ', 'D. jià'], correctAnswer: 1, analysis: '"假期"的"假"读jià。' },
  { id: 'py184', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 假期(jià) 假日(jià)', 'B. 假期(jiǎ) 假装(jiǎ)', 'C. 假期(jià) 假条(jià)', 'D. 假期(jiǎ) 假造(jiǎ)'], correctAnswer: 0, analysis: 'A项正确。"假装"的"假"读jiǎ。' },
  { id: 'py185', type: 'pinyin', question: '"朝代"的"朝"读：', options: ['A. cháo', 'B. zhāo', 'C. cháo', 'D. zhāo'], correctAnswer: 0, analysis: '"朝代"的"朝"读cháo。' },
  { id: 'py186', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 朝代(cháo) 朝向(cháo)', 'B. 朝代(zhāo) 朝气(zhāo)', 'C. 朝代(cháo) 朝廷(cháo)', 'D. 朝代(cháo) 朝向(cháo)'], correctAnswer: 1, analysis: 'B项"朝代"的"朝"应读cháo。' },
  { id: 'py187', type: 'pinyin', question: '"投奔"的"奔"读：', options: ['A. bēn', 'B. bèn', 'C. bēn', 'D. bèn'], correctAnswer: 1, analysis: '"投奔"的"奔"读bèn。' },
  { id: 'py188', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 投奔(bèn) 奔跑(bēn)', 'B. 投奔(bèn) 奔赴(bèn)', 'C. 投奔(bēn) 奔丧(bēn)', 'D. 投奔(bèn) 奔波(bō)'], correctAnswer: 0, analysis: 'A项正确。"奔跑"的"奔"读bēn。' },
  { id: 'py189', type: 'pinyin', question: '"方便"的"便"读：', options: ['A. biàn', 'B. pián', 'C. biàn', 'D. pián'], correctAnswer: 1, analysis: '"方便"的"便"读pián。' },
  { id: 'py190', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 方便(pián) 便宜(pián)', 'B. 方便(biàn) 便利(biàn)', 'C. 方便(pián) 便当(biàn)', 'D. 方便(biàn) 随便(biàn)'], correctAnswer: 2, analysis: 'C项"便当"的"便"应读biàn。' },
  { id: 'py191', type: 'pinyin', question: '"和睦"的"和"读：', options: ['A. hé', 'B. hè', 'C. huó', 'D. huò'], correctAnswer: 0, analysis: '"和睦"的"和"读hé。' },
  { id: 'py192', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 和睦(hé) 和谐(hé)', 'B. 和睦(hè) 附和(hè)', 'C. 和睦(hé) 和平(hé)', 'D. 和睦(huó) 和面(huó)'], correctAnswer: 0, analysis: 'A项正确。"附和"的"和"读hè。' },
  { id: 'py193', type: 'pinyin', question: '"宿舍"的"舍"读：', options: ['A. shě', 'B. shè', 'C. shě', 'D. shè'], correctAnswer: 1, analysis: '"宿舍"的"舍"读shè。' },
  { id: 'py194', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 宿舍(shè) 寒舍(shè)', 'B. 宿舍(shě) 舍不得(shě)', 'C. 宿舍(shè) 舍下(shè)', 'D. 宿舍(shě) 施舍(shě)'], correctAnswer: 1, analysis: 'B项"宿舍"的"舍"应读shè。' },
  { id: 'py195', type: 'pinyin', question: '"着急"的"着"读：', options: ['A. zhe', 'B. zháo', 'C. zhuó', 'D. zhāo'], correctAnswer: 1, analysis: '"着急"的"着"读zháo。' },
  { id: 'py196', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 着急(zháo) 着凉(zháo)', 'B. 着急(zhe) 沿着(zhe)', 'C. 着急(zháo) 着火(zháo)', 'D. 着急(zhāo) 着数(zhāo)'], correctAnswer: 1, analysis: 'B项正确。"着凉"的"着"读zháo。' },
  { id: 'py197', type: 'pinyin', question: '"参差"的读音是：', options: ['A. cēn cī', 'B. cēn cī', 'C. cēn cī', 'D. cēn cī'], correctAnswer: 0, analysis: '"参差"读cēn cī。' },
  { id: 'py198', type: 'pinyin', question: '下列加点字读音有误的一项是：', options: ['A. 参差(cēn cī) 参差(cēn)', 'B. 参差(cī cī) 参差(cēn)', 'C. 参差(cēn cī) 参差(cī)', 'D. 参差(cēn cī) 参差(cēn)'], correctAnswer: 1, analysis: 'B项"参差"的读音应读cēn cī。' },
  { id: 'py199', type: 'pinyin', question: '"翘首"的"翘"读：', options: ['A. qiáo', 'B. qiào', 'C. qiáo', 'D. qiào'], correctAnswer: 0, analysis: '"翘首"的"翘"读qiáo。' },
  { id: 'py200', type: 'pinyin', question: '下列加点字注音完全正确的一项是：', options: ['A. 翘首(qiáo) 翘起(qiào)', 'B. 翘首(qiào) 翘首(qiáo)', 'C. 翘首(qiáo) 翘望(qiáo)', 'D. 翘首(qiào) 翘起(qiáo)'], correctAnswer: 0, analysis: 'A项正确。"翘起"的"翘"读qiào。' }
]

module.exports = { EXTENDED_PINYIN }
